-- 생일 3월, 여성, 전화번호 유, 회원아이디 기준 오름차순
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM Member_profile
WHERE DATE_FORMAT(DATE_OF_BIRTH, "%m")='03' AND GENDER='W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC